"""
PDF Export Module for AIIA Academia-Industry Skill Assessment Platform
------------------------------------------------------------------------
Generates a clean, professional PDF summary of a student's digital portfolio,
including overall match score, verified skills, and top skill gap recommendations.
"""

from fpdf import FPDF
from fpdf.enums import XPos, YPos
from typing import Dict, List, Any, Union


def clean_text(text: Any) -> str:
    """
    Sanitizes string input to prevent latin-1 character encoding errors in FPDF.
    Replaces common non-latin-1 unicode symbols and emojis with safe ASCII equivalents.
    """
    if text is None:
        return ""
    if not isinstance(text, str):
        text = str(text)

    replacements = {
        "—": "-",
        "–": "-",
        "“": '"',
        "”": '"',
        "‘": "'",
        "’": "'",
        "✓": "[Verified]",
        "★": "*",
        "☆": "",
        "📊": "",
        "🎓": "",
        "🎯": "",
        "📅": "",
        "🏛️": "",
        "🚀": "",
        "📥": "",
        "🟢": "",
        "🟠": "",
        "🔴": "",
        "📜": "",
        "💻": "",
        "🕸️": "",
        "✅": "",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)

    return text.encode("latin-1", "replace").decode("latin-1")


class PortfolioPDF(FPDF):
    def __init__(self, platform_name: str = "Oppenheimer Skill Portal"):
        super().__init__()
        self.platform_name = platform_name

    def header(self):
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(100, 116, 139)  # slate gray
        self.cell(0, 6, clean_text(self.platform_name.upper()), new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="R")
        self.set_draw_color(203, 213, 225)
        self.set_line_width(0.4)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        page_str = f"Page {self.page_no()}"
        self.cell(
            0,
            10,
            clean_text(f"Generated by {self.platform_name} | {page_str}"),
            align="C",
        )


def generate_portfolio_pdf(
    student_info: Dict[str, Any],
    match_score: float,
    verified_skills: List[Dict[str, Any]],
    top_gaps: List[Dict[str, Any]],
    recommendations: Dict[str, List[Dict[str, Any]]],
    platform_name: str = "Oppenheimer Skill Portal"
) -> bytes:
    """
    Builds a clean, professional-looking PDF portfolio summary and returns it as bytes.

    Parameters:
    -----------
    student_info : Dict containing student metadata ('name', 'target_role', 'student_id', 'created_at')
    match_score : Float alignment percentage (0-100)
    verified_skills : List of dicts representing verified skills
    top_gaps : List of dicts representing top skill gaps/deficits
    recommendations : Dict mapping skill_id to list of recommended learning resources
    platform_name : Name of the assessment platform

    Returns:
    --------
    bytes : PDF document binary content
    """
    pdf = PortfolioPDF(platform_name=platform_name)
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Extract metadata safely
    student_name = student_info.get("name", "Student")
    target_role = student_info.get("target_role", "N/A")
    student_id = student_info.get("student_id", "N/A")
    created_at = student_info.get("created_at", "N/A")

    # -------------------------------------------------------------------------
    # 1. Document Title & Header Card
    # -------------------------------------------------------------------------
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(15, 23, 42)  # Dark slate
    pdf.cell(0, 9, clean_text("Digital Student Skill Portfolio"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(14, 116, 144)  # Cyan / Teal accent
    pdf.cell(0, 7, clean_text(f"Student: {student_name}"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(71, 85, 105)  # Muted body text
    meta_line = f"Target Role: {target_role}   |   Student ID: #{student_id}   |   Verified: {created_at}"
    pdf.cell(0, 6, clean_text(meta_line), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    # -------------------------------------------------------------------------
    # 2. Overall Match Score Display (Prominent Card)
    # -------------------------------------------------------------------------
    score_val = round(float(match_score), 1)

    # Card box background
    pdf.set_fill_color(241, 245, 249)  # Light gray blue
    pdf.set_draw_color(203, 213, 225)
    pdf.set_line_width(0.5)

    card_y = pdf.get_y()
    pdf.rect(10, card_y, 190, 20, style="FD")

    pdf.set_y(card_y + 3)
    pdf.set_x(15)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(100, 7, clean_text(f"Overall Target Role Alignment Score: {score_val}%"), new_x=XPos.RIGHT, new_y=YPos.TOP)

    # Alignment Badge text
    if score_val >= 75.0:
        badge_text = "STATUS: HIGH ALIGNMENT (Industry Ready)"
        pdf.set_text_color(16, 185, 129)  # Green
    elif score_val >= 50.0:
        badge_text = "STATUS: MODERATE ALIGNMENT (Action Plan Needed)"
        pdf.set_text_color(245, 158, 11)  # Amber
    else:
        badge_text = "STATUS: SIGNIFICANT DEFICIT (Priority Gap)"
        pdf.set_text_color(239, 68, 68)  # Red

    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(80, 7, clean_text(badge_text), new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="R")

    pdf.set_y(card_y + 24)

    # -------------------------------------------------------------------------
    # 3. Verified Skills Section
    # -------------------------------------------------------------------------
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 8, clean_text("1. Verified Skills"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_draw_color(14, 116, 144)
    pdf.set_line_width(0.8)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    if not verified_skills:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 6, clean_text("No verified skills recorded yet."), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(4)
    else:
        # Table Header
        pdf.set_fill_color(226, 232, 240)
        pdf.set_draw_color(203, 213, 225)
        pdf.set_line_width(0.2)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(30, 41, 59)

        pdf.cell(90, 7, clean_text("Skill Name"), border=1, fill=True)
        pdf.cell(50, 7, clean_text("Category"), border=1, fill=True)
        pdf.cell(50, 7, clean_text("Verified Level"), border=1, fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")

        # Table Rows
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(51, 65, 85)

        for idx, item in enumerate(verified_skills):
            fill_row = (idx % 2 == 1)
            if fill_row:
                pdf.set_fill_color(248, 250, 252)

            s_name = item.get("name") or item.get("skill_name") or "Skill"
            s_cat = item.get("category", "TECHNICAL")
            s_rating = item.get("rating") or item.get("level") or item.get("student_level", 0)

            rating_str = f"{s_rating} / 5"

            pdf.cell(90, 6.5, clean_text(s_name), border=1, fill=fill_row)
            pdf.cell(50, 6.5, clean_text(s_cat), border=1, fill=fill_row)
            pdf.cell(50, 6.5, clean_text(rating_str), border=1, fill=fill_row, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")

        pdf.ln(6)

    # -------------------------------------------------------------------------
    # 4. Skills in Progress Section
    # -------------------------------------------------------------------------
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 8, clean_text("2. Skills in Progress & Learning Pathways"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_draw_color(14, 116, 144)
    pdf.set_line_width(0.8)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    if not top_gaps:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(16, 185, 129)
        pdf.cell(0, 6, clean_text("No active skill gaps! Candidate meets all requirements for target role."), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(4)
    else:
        for idx, gap in enumerate(top_gaps, 1):
            sid = gap.get("skill_id", "")
            s_name = gap.get("skill_name") or gap.get("name") or sid
            s_curr = gap.get("student_level", 0)
            s_req = gap.get("required_level", 0)
            deficit = gap.get("gap", max(0, s_req - s_curr))

            # Fetch top recommendation
            rec_list = recommendations.get(sid, []) if isinstance(recommendations, dict) else []
            top_rec = rec_list[0] if rec_list else None

            if top_rec:
                r_title = top_rec.get("title", "Recommended Course")
                r_prov = top_rec.get("provider", "Industry Partner")
                r_type = str(top_rec.get("type", "Course")).upper()
                r_dur = top_rec.get("duration", "")
                rec_str = f"[{r_type}] {r_title} ({r_prov}{' - ' + r_dur if r_dur else ''})"
            else:
                rec_str = "Curated Industry Skill Pathway / Self-Paced Learning"

            # Render gap item box
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(30, 41, 59)
            pdf.cell(0, 6, clean_text(f"{idx}. {s_name}"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(71, 85, 105)
            gap_info = f"Current Level: {s_curr}/5   |   Required Level: {s_req}/5   |   Skill Deficit: -{deficit} levels"
            pdf.cell(0, 5, clean_text(gap_info), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(14, 116, 144)
            pdf.multi_cell(0, 5, clean_text(f"Top Recommended Resource: {rec_str}"))
            pdf.ln(3)

    # -------------------------------------------------------------------------
    # 5. Export PDF Bytes
    # -------------------------------------------------------------------------
    pdf_output = pdf.output()
    if isinstance(pdf_output, (bytes, bytearray)):
        return bytes(pdf_output)
    return str(pdf_output).encode("latin-1")


if __name__ == "__main__":
    print("=== Testing PDF Export Module ===")
    sample_student = {
        "student_id": 101,
        "name": "Aditya Kumar",
        "target_role": "Data Science",
        "created_at": "2026-08-31"
    }

    sample_verified = [
        {"name": "Python Programming", "category": "TECHNICAL", "rating": 4},
        {"name": "SQL & Databases", "category": "TECHNICAL", "rating": 3},
        {"name": "Data Visualization", "category": "TECHNICAL", "rating": 4},
    ]

    sample_gaps = [
        {"skill_id": "machine_learning", "skill_name": "Machine Learning & Modeling", "student_level": 2, "required_level": 5, "gap": 3},
        {"skill_id": "stat_analysis", "skill_name": "Statistical Analysis", "student_level": 1, "required_level": 5, "gap": 4},
    ]

    sample_recs = {
        "machine_learning": [
            {"title": "Applied Machine Learning & Deep Learning", "provider": "IIT Madras / NPTEL", "type": "course", "duration": "8 weeks"}
        ],
        "stat_analysis": [
            {"title": "Statistical Methods for Data Science", "provider": "AIIA Analytics", "type": "workshop", "duration": "4 weeks"}
        ]
    }

    pdf_bytes = generate_portfolio_pdf(sample_student, 78.5, sample_verified, sample_gaps, sample_recs)
    print(f"[OK] PDF generated successfully! Byte size: {len(pdf_bytes)} bytes")
